version: '3.5'
services:
  swagger-api:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports: 
      - '27017:27017'
  kong-database:
    image: postgres:9.5
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: 123456789
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5
  kong-migration:
    image: kong:latest
    command: "kong migrations up"
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: 123456789
    links:
      - kong-database
    depends_on:
      - kong-database
  kong:
    image: kong:latest
    restart: always
    depends_on: 
      - kong-migration
      - kong-database
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=123456789
      - KONG_PG_SSL=true
      - KONG_PG_SSL_VERIFY=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 5s
      timeout: 2s
      retries: 10

  taxi-api-1:
    image: pap133/taxi-api2:v1.0.0
    restart: always
    links:
      - mongo
      - kong
    expose:
      - 10010
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10010/health"]
      interval: 5s
      timeout: 2s
      retries: 10

  taxi-api-2:
    image: pap133/taxi-api2:v1.0.0
    restart: always
    links:
      - mongo
      - kong
    expose:
      - 10010
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10010/health"]
      interval: 5s
      timeout: 2s
      retries: 10
